#!/bin/sh

# PROVIDE: TagCoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# TagCoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable TagCoin service.
# TagCoin_config (path): Set to /usr/local/etc/TagCoin.conf by default.
# TagCoin_user:  The user account TagCoin daemon runs as. It uses 'root' user by default.
# TagCoin_group: The group account TagCoin daemon runs as. It uses 'wheel' group by default.
# TagCoin_datadir (str): Default to "/var/db/TagCoin". Base data directory.

. /etc/rc.subr

name=TagCoin
rcvar=TagCoin_enable

: ${TagCoin_enable:=NO}
: ${TagCoin_config=/usr/local/etc/TagCoin.conf}
: ${TagCoin_datadir=/var/db/TagCoin}
: ${TagCoin_user="root"}
: ${TagCoin_group="wheel"}

required_files=${TagCoin_config}
command=/usr/local/bin/TagCoind
TagCoin_chdir=${TagCoin_datadir}
pidfile="${TagCoin_datadir}/TagCoind.pid"
stop_cmd=TagCoin_stop
command_args="-conf=${TagCoin_config} -datadir=${TagCoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

TagCoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${TagCoin_datadir}
	[ $? -eq 0 ] && chown -R ${TagCoin_user}:${TagCoin_group} ${TagCoin_datadir}
}

TagCoin_prestart()
{
	if [ ! -d "${TagCoin_datadir}/." ]; then
		TagCoin_create_datadir || return 1
	fi
}

TagCoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

TagCoin_stop()
{
    TagCoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${TagCoin_config} -datadir=${TagCoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
